name: "Select Environment"
description: "Fetch an secret from AWS Parameter Store"

inputs:
  test-branch:
    description: "Test Branch that can be passed to trigger deploys outside the standard ones"
    required: true

outputs:
  environment:
    description: "Environment Name"
    value: ${{steps.select-environment.outputs.environment}}
  release-tag:
    description: "Release Tag"
    value: ${{steps.select-environment.outputs.release-tag}}

runs:
  using: "composite"
  steps:
    - name: Select Environment
      shell: bash
      id: select-environment
      # env:
      #   COMMIT_TAG: ${{ inputs.commit-tag }}
      #   GITHUB_RUN_ID: ${{ inputs.github-run-id }}
      #   GITHUB_RUN_NUMBER: ${{ inputs.github-run-number }}

      run: |

        # PREPARE TAG CHECKING TO DETERMINE WHETHER IS PROD, STAGING or DEV
        export PROD_BRANCH='main'
        export STG_BRANCH='staging'
        export DEV_BRANCH='dev'
        export REGEX_DEVOPS='${{ inputs.test-branch }}'

        if [[ "${GITHUB_REF_NAME}" == "$PROD_BRANCH" ]]; then
            echo "PROD TAGS"
            ENVIRONMENT="prod"
        elif [[ "${GITHUB_REF_NAME}" == "$STG_BRANCH" ]]; then
            echo "STG TAGS"
            ENVIRONMENT="staging"
        elif [[ "${GITHUB_REF_NAME}" == "$DEV_BRANCH" ]]; then
            echo "DEV TAGS"
            ENVIRONMENT="dev"
        elif [[ ${GITHUB_REF_NAME} =~ $REGEX_DEVOPS ]]; then
            echo "DEV TAGS"
            ENVIRONMENT="dev"
        else
            echo ${GITHUB_REF_NAME}
            echo "This is not a valid tag, exiting ..."
            exit 1
        fi

        RELEASE_TAG="${ENVIRONMENT}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}-${GITHUB_RUN_ATTEMPT}"

        # OUTPUTS
        echo "::set-output name=environment::$ENVIRONMENT"
        echo "::set-output name=release-tag::$RELEASE_TAG"
