name: "Install ARGOCD CLI"
description: "Install INFRALESS Deployment Tools"

runs:
  using: "composite"
  steps:
    - name: Install ARGOCD CLI
      shell: bash
      id: install_argocd_cli
      run: |

        # INSTALL ARGOCD CLI
        sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.1.2/argocd-linux-amd64
        sudo chmod +x /usr/local/bin/argocd
