name: devops-build
on:
  workflow_call:
    inputs:
      aws-account-id:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      app-image-name:
        required: true
        type: string
    outputs:
      environment:
        value: ${{ jobs.build.outputs.environment }}
      release-tag:
        value: ${{ jobs.build.outputs.release-tag }}
      aws-region:
        value: ${{ inputs.aws-region }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.select-environment.outputs.environment }}
      release-tag: ${{ steps.select-environment.outputs.release-tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Select Environment
        id: select-environment
        uses: LUPARG/c-github-actions/.github/actions/select-environment@0.0.11

      - name: Assume InfraDeployGitHub
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: "${{ inputs.aws-region }}"
          role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/CIDeployGitHub
          role-duration-seconds: 1800

      - name: Install AWS CLI
        id: install-aws-cli
        uses: LUPARG/c-github-actions/.github/actions/install-aws-cli@0.0.11

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push to ECR - PHP Version
        id: build-push-ecr-php
        uses: LUPARG/c-github-actions/.github/actions/build-push-ecr-php@0.0.11
        with:
          aws-account-id: ${{ inputs.aws-account-id }}
          aws-region: "${{ inputs.aws-region }}"
          app-image-name: ${{ inputs.app-image-name }}
          release-tag: ${{steps.select-environment.outputs.release-tag}}
